name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main] # Замяні 'main' на сваю галіну, калі патрэбна

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Галіна для разгортвання
          folder: dist # Тэчка, якая змяшчае сабраны праект
          token: ${{ secrets.GH_TOKEN }} # Выкарыстанне створанага токена
